version: "3.8"

services:
  apps:
    container_name: apps
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on: 
      - postgres
    ports:
      - 3000:3000
      - 9229:9229
      - 8080:8080
    networks:
      - lem-network
    volumes:
      - .:/app
      - /app/node_modules
    restart: on-failure
    env_file: 
      - ./apps/api/.env
  postgres:
    image: postgres:alpine
    restart: always
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
    lem-network:
