version: "3.8"

services:
  apps:
    container_name: apps
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
      - 9229:9229
      - 4200:4200
    networks:
      - lem-network
    volumes:
      - .:/app
    restart: on-failure

networks:
    lem-network:
